version: '3.8'

networks:
  brainbytes-network:
    driver: bridge

services:
  # Frontend container
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:3000" # Ensure the frontend port matches the app configuration
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - brainbytes-network

  # Backend API container
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./backend/.env # Use an .env file for environment variables
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - brainbytes-network

  # MongoDB container
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - brainbytes-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.stats()"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongo-data:
    driver: local