name: BrainBytes Deploy

on:
  workflow_run:
    workflows:
      - BrainBytes Lint
      - BrainBytes Test
      - BrainBytes Docker Build
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./DevOps/brainbytes-multi-container/frontend
          file: ./DevOps/brainbytes-multi-container/frontend/Dockerfile
          push: true
          tags: d1tt0/brainbytes-frontend:latest

      - name: Push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./DevOps/brainbytes-multi-container/backend
          file: ./DevOps/brainbytes-multi-container/backend/Dockerfile
          push: true
          tags: d1tt0/brainbytes-backend:latest

      # Optional: Deploy via SSH
      # - name: SSH to server and redeploy
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       docker pull jayceebasa/brainbytes-frontend:latest
      #       docker pull jayceebasa/brainbytes-backend:latest
      #       docker-compose down
      #       docker-compose up -d --remove-orphans
