name: BrainBytes Lint

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      # Step 3: Debug - List files in frontend and backend
      - name: List files in frontend
        run: ls -R ./DevOps/brainbytes-multi-container/frontend

      - name: List files in backend
        run: ls -R ./DevOps/brainbytes-multi-container/backend

      # Step 4: Frontend linting
      - name: Install frontend dependencies
        working-directory: ./DevOps/brainbytes-multi-container/frontend
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Lint frontend code
        working-directory: ./DevOps/brainbytes-multi-container/frontend
        run: npm run lint

      # Step 5: Backend linting
      - name: Install backend dependencies
        working-directory: ./DevOps/brainbytes-multi-container/backend
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Lint backend code
        working-directory: ./DevOps/brainbytes-multi-container/backend
        run: npm run lint